image: ubuntu:focal

build:
  stage: build 
  only:
    - schedules
  before_script:
     - apt-get update
     # Prevent interactive prompt when installing tzdata
     - DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
     # Install essential build tools
     - apt-get -y install build-essential
  script:
     - make JOBS= dist
  artifacts:
    paths:
      - dist/morpheus.deb
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  only:
    - schedules
  script:
    - echo
