image: ubuntu:focal

build:
  stage: build 
  only:
    - schedules
  before_script:
     - apt update
     # Prevent interactive prompt when installing tzdata
     - DEBIAN_FRONTEND=noninteractive apt -y install tzdata
     - apt -y install build-essential cmake gcc-multilib
  script:
     - make dist-configure
     - make dist-build
     - make dist-install
  artifacts:
    paths:
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  only:
    - schedules
  script:
    - echo
