image: ubuntu:focal

build:
  stage: build 
  #only:
  #  - schedules
  before_script:
     - apt-get update
     # Prevent interactive prompt when installing tzdata
     - DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
     # Install essential build tools
     - apt-get -y install build-essential
  script:
     # Message from ICTS: CPU limit is implemented by using kernel throttling,
     # so it’s imported to correctly set the maximum number of threats in the
     # CI/CD jobs, otherwise the response-time will slow down.
     - make JOBS=10 dist
  artifacts:
    paths:
      - dist/morpheus.deb
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  #only:
  #  - schedules
  script:
    - echo
