image: gcc

build:
  stage: build 
  only:
    - schedules
  before_script:
     - apt update && apt -y install make cmake
  script:
    - make configure
    - make build
  artifacts:
    paths:
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  only:
    - schedules
  script:
    - echo
