image: gcc

build:
  stage: build 
  only:
    - schedules
  before_script:
     - apt update && apt -y install make cmake ninja-build gcc-multilib
  script:
    - mkdir build
    - mkdir install
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../install -G Ninja -C ../clang/cmake/caches/DistributionExample.cmake ../llvm
    - ninja stage2-distribution
    - ninja stage2-install-distribution
  artifacts:
    paths:
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  only:
    - schedules
  script:
    - echo
